title: בית
views:
  - title: Floorplan
    path: floorplan
    theme: Google Dark Theme
    badges: []
    cards:
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: "custom:floorplan-card"
                full_height: true
                config:
                  image: /local/floorplan/home/home.svg
                  stylesheet: /local/floorplan/home/home.css
                  log_level: info
                  console_log_level: info
                  defaults:
                    hover_action: hover-info
                    tap_action: more-info
                  rules:
                    - entity: switch.tuya_socket
                      element: switch.tuya_socket
                      state_action:
                        action: call-service
                        service: floorplan.image_set
                        service_data: "/local/floorplan/home/light_${entity.state}.svg"
                      tap_action: toggle
                    - entity: switch.tuya_socket
                      element: switch.tuya_socket.button
                      state_action:
                        action: call-service
                        service: floorplan.class_set
                        service_data: "button-${entity.state}"
                      tap_action:
                        action: call-service
                        service: homeassistant.toggle
                    - entity: switch.tuya_socket
                      element: switch.tuya_socket.text
                      state_action:
                        action: call-service
                        service: floorplan.text_set
                        service_data: "${entity.state}"
                      tap_action: false
                    - entity: switch.living_area_fan
                      tap_action: false
                      state_action:
                        action: call-service
                        service: floorplan.class_set
                        service_data:
                          class: '${(entity.state === "on") ? "spinning" : ""}'
                    - entity: switch.living_area_fan
                      element: switch.living_area_fan.button
                      state_action:
                        action: call-service
                        service: floorplan.class_set
                        service_data: "button-${entity.state}"
                      hold_action:
                        action: call-service
                        service: homeassistant.toggle
                        service_data:
                          entity_id: switch.living_area_fan
                    - entity: switch.living_area_fan
                      element: switch.living_area_fan.text
                      state_action:
                        action: call-service
                        service: floorplan.text_set
                        service_data: "${entity.state}"
                      tap_action: false
                    - entity: camera.zagreb_ban_jelacic_square
                      state_action:
                        action: call-service
                        service: floorplan.image_set
                        service_data:
                          image: "${entity.attributes.entity_picture}"
                          image_refresh_interval: 10
                    - entities:
                        - binary_sensor.main_bedroom
                        - binary_sensor.living_area
                      state_action:
                        action: call-service
                        service: floorplan.style_set
                        service_data:
                          style: >
                            fill: ${ entity.state === "on" ? "#F9D27C" : "#7CB1F9"
                            };

                            transition: ${ entity.state === "off" ? "fill 5s ease"
                            : "" };
