title: My Awesome Home
views:
  # View tab title.
  - title: Example
    cards:
      # The markdown card will render markdown text.
      - type: markdown
        title: Lovelace
        content: >
          Welcome to your **Lovelace UI**.
      - type: custom:todoist-task-list
        entity: calendar.inbox
        title: TodoIst inbox
